packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@mahjong/*"

engineStrict: true

strictPeerDependencies: true

allowBuilds:
  esbuild: true
  workerd: true
