import { parseHongKongProfile } from "./hong-kong-profile.js";

export const hongKongV1Profile = parseHongKongProfile({
  profileId: "hong-kong/v1",
  ruleset: {
    id: "hong-kong",
    version: 1,
    status: "provisional",
  },
  decisions: [
    "HK-001",
    "HK-002",
    "HK-003",
    "HK-004",
    "HK-005",
    "HK-006",
    "HK-007",
    "HK-008",
    "HK-009",
    "HK-010",
    "HK-011",
    "HK-013",
  ],
  tileSet: {
    totalTiles: 144,
    suitedCopies: 4,
    honorCopies: 4,
    seasons: 4,
    flowers: 4,
    bonusesEnabled: true,
    canonicalTileIdOrder: "v1-suits-honors-seasons-flowers",
  },
  seating: {
    turnOrder: ["east", "south", "west", "north"],
    dealerSeat: "east",
    initialDealerSelection: "uniform-random-table-position",
  },
  wall: {
    representation: "deterministically-shuffled-linear-sequence",
    simulateDiceBreak: false,
    ordinaryDrawEnd: "head",
    bonusReplacementDrawEnd: "tail",
    deadWall: "none",
    emptyWhen: "head-passes-tail",
    exhaustiveDrawTrigger: "required-draw-unavailable",
  },
  deal: {
    packetSize: 4,
    packetRounds: 3,
    finalDrawOrder: ["east", "east", "south", "west", "north"],
    initialTileSlots: {
      east: 14,
      south: 13,
      west: 13,
      north: 13,
    },
  },
  bonusReplacement: {
    initialSeatOrder: ["east", "south", "west", "north"],
    initialBonusOrder: "deal-acquisition-order",
    completeSeatBeforeNext: true,
    completeReplacementChainBeforeNextBonus: true,
    recursivelyReplaceBonuses: true,
    replacementSource: "tail",
    exposeImmediately: true,
    failedReplacement: "exhaustive-draw",
    requiredStructuralTiles: {
      east: 14,
      south: 13,
      west: 13,
      north: 13,
    },
  },
  ordinaryTurn: {
    dealerOpensByDiscarding: true,
    drawSource: "head",
    replaceDrawnBonusesRecursively: true,
    discardStructuralTiles: 1,
    structuralTilesBetweenTurns: 13,
    structuralTilesBeforeDiscard: 14,
    advanceAfterUnclaimedDiscard: "next-seat-in-turn-order",
  },
});
